export const GET_POKEMONS = "GET_POKEMONS";
export const GET_TYPES = "GET_TYPES";
export const SET_INDEX_PAGE = "SET_INDEX_PAGE";
export const POST_POKEMON = "POST_POKEMON";

export const GET_POKEMON_BY_NAME_OR_ID = "GET_POKEMON_BY_NAME_OR_ID";
export const GET_DETAILS = "GET_DETAILS";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
